---

- block:
    - name: check for iso file
      win_stat:
        path: '{{ vbox_iso_file }}'
        get_checksum: no
      register: check_vbox_iso_file

    - name: download iso file if needed
      win_get_url:
        url: '{{ vbox_guest_additions_download_url }}'
        dest: '{{ vbox_iso_file }}'
      when: not check_vbox_iso_file.stat.exists

    - name: mount iso
      win_disk_image:
        image_path: '{{ vbox_iso_file }}'
        state: present
      register: disk_image_out

    - name: ensure vbox certs installed
      win_certificate_store:
        path: '{{ disk_image_out.mount_paths[0] }}cert\{{ item }}'
        state: present
        key_storage: machine
        store_name: TrustedPublisher
      loop:
        - vbox-sha256.cer
        - vbox-sha1.cer

    - name: ensure vbox guest additions installed
      win_package:
        path: '{{ disk_image_out.mount_paths[0] }}VBoxWindowsAdditions.exe'
        creates_path: 'C:\Program files\Oracle\VirtualBox'
        arguments:
          - /S

  always:

    - name: unmount iso
      win_disk_image:
        image_path: '{{ vbox_iso_file }}'
        state: absent

    - name: remove iso file
      win_file:
        path: '{{ vbox_iso_file }}'
        state: absent